services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    ports:
      - '5006:5006'
    volumes:
      - /server/actual/actual-data:/data
    restart: unless-stopped
