services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    volumes:
      - /server/code-server/config:/config
    ports:
      - 8445:8443
    restart: unless-stopped
    env_file:
      - ../stack.env
