version: '3.8'
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
    image: ghcr.io/wg-easy/wg-easy
    container_name: vpn
    volumes:
      - /server/wireguard:/etc/wireguard
    ports:
      - '51820:51820/udp'
      - '51821:51821/tcp'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
