version: '3.9'
services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest
    restart: unless-stopped
    ports:
      - '1738:8080'
    volumes:
      - '/server/gatus:/config'
    env_file:
      - ../stack.env
