ghost-server:
  image: ghost:5
  cap_add:
    - CAP_SYS_NICE
  security_opt:
    - seccomp:unconfined
  restart: unless-stopped
  ports:
    - 2368:2368
  depends_on:
    - ghost-db
  volumes:
    - /server/ghost/content:/var/lib/ghost/content
  env_file:
    - ../stack.env
