services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /server/heimdall/config:/config
    ports:
      - 8866:80
      - 4433:443
    restart: unless-stopped
