services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/unaspro:/library
      - /server/jellyfin/config:/config
      - /server/jellyfin/cache:/cache
      - type: bind
        source: /server/jellyfin/media
        target: /media
      - type: bind
        source: /server/jellyfin/media2
        target: /media2
        read_only: true
      - type: bind
        source: /server/jellyfin/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    #environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    
