version: '3.0'
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    volumes:
      - /server/memos/:/var/opt/memos
    ports:
      - 5230:5230
