services:
  n8n:
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: n8n
    environment:
      PUID: 1000
      PGID: 1000
      N8N_HOST: n8n.chrisstayte.com
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://n8n.chrisstayte.com
    ports:
      - 5678:5678
    volumes:
      - /server/n8n:/home/node/.n8n
    image: docker.n8n.io/n8nio/n8n
