services:
  nginx:
    image: nginx:latest
    container_name: nginx-chrisstayte-app
    ports:
      - '1110:80'
    volumes:
      - /server/websites/chrisstayte.app:/usr/share/nginx/html:ro
    restart: unless-stopped
