services:
  nginx:
    image: nginx:latest
    container_name: nginx-backendwarehouse-com
    ports:
      - '1112:80'
    volumes:
      - /server/websites/backendwarehouse.com:/usr/share/nginx/html:ro
    restart: unless-stopped
