services:
  nginx:
    image: nginx:latest
    container_name: nginx-chrisstayte-com
    ports:
      - '1111:80'
    volumes:
      - /server/websites/chrisstayte.com:/usr/share/nginx/html:ro
    restart: unless-stopped
